#!/bin/bash

[[ $- != *i* ]] && return

if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
    fi
fi

export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export GPG_TTY=$(tty)
export GREP_COLOR='97;45'

[ -f ~/.zsh_aliases ] && { . ~/.zsh_aliases;}
[ -f ~/.zsh_functions ] && { . ~/.zsh_functions;}

{
  alias ls='ls -Q --classify --group-directories-first --color=auto'
  alias l='ls -lh'
  alias ll='ls -lah'

  alias ..='cd ..'
  alias ...='cd ../..'

  alias cp='cp -v'
  alias mv='mv -v'
  alias rm='rm -v --preserve-root'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'

  alias ne='sudo netstat -ntupe | sort -r | grep ESTABLISHED'
  alias nl="sudo netstat -ntupl | sort -r | egrep '[0.]{7}'"
  alias net='sudo netstat -ntpe | sort -r | grep ESTABLISHED'
  alias nlt="sudo netstat -ntpl | sort -r | egrep '[0.]{7}'"
  alias neu='sudo netstat -nupe | sort -r | grep ESTABLISHED'
  alias nlu="sudo netstat -nupl | sort -r | egrep '[0.]{7}'"
  alias nec='sudo netstat -ntpe | sort -r | grep TIME_WAIT'
  alias nes='sudo netstat -ntpe | sort -r | grep CLOSED_WAIT'
}
