listen_addresses = ['0.0.0.0:53']
server_names = ['NextDNS-ea1a22']

#
# Caching
#

cache = true
cache_max_ttl = 86400
cache_min_ttl = 2400
cache_neg_max_ttl = 600
cache_neg_min_ttl = 60
cache_size = 4096

#
# Servers
#

ipv4_servers = true
ipv6_servers = true
dnscrypt_servers = true
doh_servers = true

require_dnssec = true
require_nofilter = true
require_nolog = true

block_ipv6 = false
block_undelegated = true
block_unqualified = true

#
# Connections
#

max_clients = 256

force_tcp = false
keepalive = 30  # s
timeout = 5000  # ms
http3 = true

#
# Privacy
#

ignore_system_dns = true
dnscrypt_ephemeral_keys = true
tls_disable_session_tickets = true

#
# Logging
#

log_file = 'dnscrypt-proxy.log'
log_file_latest = false
log_files_max_age = 1
log_files_max_backups = 1
log_files_max_size = 10  # MB
log_level = 2

[query_log]
file = 'dnscrypt-query.log'
format = 'ltsv'

[nx_log]
file = 'dnscrypt-nx.log'
format = 'ltsv'

#
# Sources
#

[sources]
[sources.'public-resolvers']
urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md']
cache_file = 'public-resolvers.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 72
prefix = ''

[static]
[static.'NextDNS-ea1a22']
stamp = 'sdns://AgEAAAAAAAAACjQ1LjkwLjI4LjAADmRucy5uZXh0ZG5zLmlvBy9lYTFhMjI'
