BACKEND="/usr/lib/x86_64-linux-gnu/sshg-fw-iptables"
LOGREADER="LANG=C /bin/journalctl -afb -p info -n1 -o cat SYSLOG_FACILITY=4 SYSLOG_FACILITY=10"
THRESHOLD=10
BLOCK_TIME=900
DETECTION_TIME=21600
IPV6_SUBNET=64
IPV4_SUBNET=32
WHITELIST_FILE=/etc/sshguard/whitelist
