# dnscrypt-proxy.toml

block_ipv6 = true
cache = true
cache_max_ttl = 86400
cache_min_ttl = 900
cache_neg_max_ttl = 600
cache_neg_min_ttl = 60
cache_size = 4096
cert_refresh_delay = 60
dnscrypt_servers = true
doh_servers = true
force_tcp = false
ignore_system_dns = true
ipv4_servers = true
ipv6_servers = false
keepalive = 30
listen_addresses = ['0.0.0.0:53']
log_file = '/var/log/dnscrypt-proxy/dnscrypt-proxy.log'
log_files_max_age = 7
log_files_max_backups = 1
log_files_max_size = 10
log_level = 2
max_clients = 100
require_dnssec = true
require_nofilter = true
require_nolog = true
server_names = ['NextDNS-ea1a22']
timeout = 3000  # ms

[sources]
  [sources.'public-resolvers']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md']
  cache_file = 'public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''

[static]
  [static.'NextDNS-ea1a22']
  stamp = 'sdns://AgEAAAAAAAAACjQ1LjkwLjI4LjAADmRucy5uZXh0ZG5zLmlvBy9lYTFhMjI'

[query_log]
  file = '/var/log/dnscrypt-proxy/query.log'
  format = 'tsv'
  ignored_qtypes = ['NS']

[nx_log]
  file = '/var/log/dnscrypt-proxy/nx.log'
  format = 'tsv'
