#!/usr/bin/env zsh

alias em="$(which emacs)"
alias nano='nano -E -D -A -m -u'

{
  [ -d "${HOME}/Downloads" ] && alias d="cd ${HOME}/Downloads"
  [ -d "/keybase/private/initbar" ] && alias k="cd /keybase/private/initbar"
  [ -d /sandbox ] && alias s='cd /sandbox'
  [ -d /cache ] && alias c='cd /cache'
  [ -d /tmp ] && alias t='cd /tmp'

  alias df="df -hl | grep -v Filesystem | sort | egrep -i '[0-9]+%'"
  alias du='du -xch'
  alias fr="free -lh | egrep 'total|used|free' -A5"
  alias gl='glances -t2 -1 -d'
  alias gsutil='gsutil -m'
  alias host='host -t any -v -l'
  alias htop="htop -u ${USER}"
  alias iotop='sudo iotop -o -a'
  alias ipt="sudo iptables -L -v -n --line-numbers | egrep 'Chain [A-Za-z0-9-]+' -A100000"
  alias lspci='lspci -tv'
  alias lsusb='lsusb -tv'
  alias mosh='mosh -n'
  alias ser='sudo service --status-all | grep +'
  alias sort="sort --parallel=$(nproc)"
  alias w='w -hus'

  {
    alias ls='ls -Q --classify --group-directories-first --color=auto'
    [ -n "$(which ls++)" ] && {
      alias l='ls++ --potsf'
      alias ll='ls++ --potsf -a'
    } || {
      alias l='ls -lh'
      alias ll='ls -lah'
    }
  }

  {
    alias ..='cd ..'
    alias cp='cp -v'
    alias cpr='rsync -ahHAXu --progress'
    alias mv='mv -v'
    alias rm='rm -v --preserve-root'
  }

  {
    alias egrep='egrep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias grep='grep --color=auto'
  }

  {
    alias ne='sudo netstat -ntupe | sort -r | grep ESTABLISHED'
    alias nec='sudo netstat -ntpe | sort -r | grep TIME_WAIT'
    alias nes='sudo netstat -ntpe | sort -r | grep CLOSED_WAIT'
    alias net='sudo netstat -ntpe | sort -r | grep ESTABLISHED'
    alias neu='sudo netstat -nupe | sort -r | grep ESTABLISHED'
    alias nl="sudo netstat -ntupl | sort -r | egrep '[0.]{7}'"
    alias nlt="sudo netstat -ntpl | sort -r | egrep '[0.]{7}'"
    alias nlu="sudo netstat -nupl | sort -r | egrep '[0.]{7}'"
  }

  {
    alias ddf='sync -f'
    alias ddt="cat /proc/vmstat | egrep 'dirty|write'"
  }

  {
    alias shd='shred -n 1 -u -z -f -v'
    alias srm='srm -d -r -v'
  }

  {
    alias de="docker exec"
    alias di="docker images"
    alias dl="docker logs"
    alias dp="docker ps"
  }

  {
    [ -d /media/veracrypt64 ] && alias m='cd /media/veracrypt64'
    alias getm='veracrypt -t /dev/sdb1 /media/veracrypt64'
    alias setm='veracrypt -d /media/veracrypt64'
  }
}

{
  alias lssnort='ls /etc/snort/rules/'
  alias aireplay-ng='aireplay-ng -Q -T4 -B'
  alias arp="arp -n | egrep -v 'incomplete|address' | sort -g"
  alias arping='arping -f -c 1 -w 5'
  alias cppcheck='cppcheck --enable=all'
  alias curl='curl -js -4 --compressed --globoff'
  alias dotdotpwn="cd ${HOME}/storj/stack/dotdotpwn && perl dotdotpwn.pl"
  alias flawfinder='flawfinder -F -C --dataonly'
  alias gdb='gdb -q'
  alias hashcat='hashcat --status --status-timer 1'
  alias lsnse='ls /usr/share/nmap/scripts/'
  alias nmap='nmap -T3 -v -n'
  alias ping='ping -D -s0 -t 255 -A -U -v -W 10'
  alias pingflood='ping -i 0.2 -f -r -D -s0 -t 255'
  alias shellcheck='shellcheck --color=always'
  alias speedtest='speedtest --secure'
  alias sqlmap='sqlmap --random-agent --level=5 --risk=3 -a -b'
  alias strace='strace -fttTCx -s 9999 -y'
  alias valgrind='valgrind --leak-check=full --show-leak-kinds=all'
  alias wpscan='docker run -it \
                     --rm wpscanteam/wpscan \
                     --random-agent \
                     --threads 2 \
                     --enumerate t \
                     --enumerate p \
                     --enumerate u \
                     --wp-content-dir custom-content \
                     --wp-plugins-dir wp-content/custom-plugins'
}

{
  alias diff='colordiff'
  alias dt="perl -pi -e 'chomp if eof'"
  alias grip='grip --norefresh'
  alias md='pygmentize -g -O ansi,style=colorful,python=cool,bg=light'
  alias strings='strings -a'

  {
    alias sa='ssh-add'
    alias sb='ssh-keygen -B -f'
    alias scp='scp -C -v'
    alias sd='ssh-add -D'
    alias sk='ssh-keygen -t rsa -b 4096 -a 2048 -E sha256 -v'
    alias ski='openssl rsa -text -noout <'
    alias skn='ssh-keygen -t rsa -b 4096 -o -a 2048 -E sha256 -v'
    alias skp='ssh-keygen -y -f'
    alias sl='ssh-add -l -c -t 3h'
    alias ssh='ssh -2 -v -C'
  }

  {
    alias gtd='g diff'
    alias gtl='g lga'
    alias gtp='g pm'
    alias gtpf='g pmf'
    alias gtpu='g pu'
    alias gtr='g rb'
    alias gts='g st'
  }

  {
    alias cpan='cpanm'
  }

  {
    alias pycc="python -OO -m py_compile"
    alias pipi='sudo -H pip2 install'
    alias pipu="pip2 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 sudo -H pip2 install -U"
    alias pip3i='sudo -H pip3 install'
    alias pip3u="pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 sudo -H pip3 install -U"
  }

  {
    alias gemu='sudo gem install rubygems-update && sudo update_rubygems && sudo gem update --system'
  }

  {
    alias gr='go run'
    alias gb='go build'
    alias gg='go get'
  }

  {
    alias rustc='rustc -C opt-level=3'
  }

  {
    alias sass="sass -C"
    alias sassm="sass -C --style compressed"
    alias sassw="sass -C --style compressed --watch ."
  }

  {
    alias yui='yui-compressor'
  }

  {
    alias pyserver='python -m SimpleHTTPServer 8000'
    alias wserverl="bundle exec jekyll server --watch --port ${1:-8080}"
    alias wserverg='bundle exec jekyll server --watch --host 0.0.0.0 --port 8080'
  }
}

{
  {
    alias pdf='evince'
    alias pdftex='xelatex'
  }

  {
    alias disp='display'
    alias ditaa='ditaa -r -S'
    alias et='exiftool'
    alias jpegm='jpegoptim -s'
  }

  {
    alias mplayer='mplayer -cache 16384'
    alias vlc='vlc -vv'

    function youtube-dl() {
      docker pull initbar/docker-youtube-dl:latest
      docker run \
             -v $PWD:/downloads \
             -u $(id -u):$(id -g) \
             --rm -d \
             initbar/docker-youtube-dl \
             "$@"
    }

    function mp3-dl() {
      docker pull initbar/docker-youtube-dl:latest
      docker run \
             -v $PWD:/downloads \
             -u $(id -u):$(id -g) \
             --rm -d \
             initbar/docker-youtube-dl \
             --extract-audio \
             --prefer-ffmpeg \
             --audio-format mp3 \
             --audio-quality 320k \
             "$1"
    }

    function ffmpeg() {
      docker pull initbar/docker-ffmpeg:latest
      docker run \
             -v $PWD:/downloads \
             -u $(id -u):$(id -g) \
             --rm \
             initbar/docker-ffmpeg \
             "$@"
    }
  }
}

{
  # alias 7z='7z -bb3'
  alias ark-secure='7z a -t7z -m0=lzma2 -mx=9 -mfb=128 -md=64m -ms=on -mhe=on -p'
  alias ark='7z a -t7z -m0=lzma2 -mx=9 -mfb=128 -md=64m -ms=on -mhe=on'
  alias xz="xz --threads=$(cat /proc/cpuinfo|grep cores|wc -l)"
}

{
  # initbar/transmission-cli
  function tcli() {
    docker pull initbar/docker-transmission-cli:latest
    docker run \
           -v ${HOME}/.torrents:/torrents \
           -p $RANDOM:9091 \
           -p $RANDOM:51413/tcp \
           -p $RANDOM:51413/udp \
           --dns 80.80.80.80 \
           --dns 8.8.8.8 \
           --rm -d \
           initbar/docker-transmission-cli \
           "$1" # magnet link
  }

  # initbar/dockfiles
  # function ds() {
  #   docker run \
  #          --rm -it \
  #          --user ubuntu \
  #          -v $PWD:/sandbox \
  #          --security-opt seccomp:unconfined \
  #          initbar/dockfiles
  # }
}
