(add-to-list 'load-path "~/.emacs.d/custom")
(load-library "packages")
(load-library "packages-config")
(load-library "general")
(load-library "shortcuts")
(load-library "aliases")
(load-library "interface")
(load-library "syntax")
