name: Build and Containerize
on:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    name: Build and Upload to Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.0.0
      with:
        dockerfile: Dockerfile
        ignore: DL3004,DL3008,DL4001,DL4006
    - name: Build Docker image
      run: docker build --tag="initbar/lib" https://github.com/initbar/lib.git#main
    - name: Login to Docker
      run: echo -n ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Upload to Docker
      run: docker image push "initbar/lib:latest"
