name: Build Docker image of dotfiles
on: [push, pull_request]
jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: docker build --tag="initbar/lib" https://github.com/initbar/dotfiles.git#master
